# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DialyCalendar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FirebaseCore'
  pod 'FirebaseFirestore'
  pod 'FirebaseAuth'
  # Pods for DialyCalendar

end
